[tool.poetry]
name = "palo-cyberark-python-bootcamp"
version = "1.0"
description = "Python Bootcamp"
readme = "README.md"
repository = "https://github.cyberng.com/azahavi/python-bootcamp"
package-mode = false

[tool.poetry.group.dev.dependencies]
# tools-configuration-cyberark = "8.*"
mockito = "*"
pylint-pydantic = "*"


[tool.poetry.dependencies]
python = "^3.13"
pydantic = "^2.0.0"
pydantic-settings = "*"
# infra-logging-cyberark = ">=3"
cachetools = "*"
tenacity = "*"
typing-extensions = "*"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
